# Generated by Django 5.0 on 2023-12-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_time_tasks_tasktime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='taskDesc',
            field=models.TextField(null=True),
        ),
    ]
