# Generated by Django 5.0 on 2023-12-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_tasks_taskdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='taskDesc',
            field=models.TextField(default=None),
        ),
    ]
